version: '3'
services:
  frontend:
    build: ./frontend
    tty: true
    ports:
      - 3000:3000
    command: yarn run dev
    volumes:
      - ./frontend:/myapp/frontend
    depends_on:
      - web

